name:                hw-yq
version:             0.1.0.0
github:              "newhoggy/hw-yq"
license:             BSD3
author:              "John Ky"
maintainer:          "newhoggy@gmail.com"
copyright:           "2016 John Ky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/newhoggy/hw-yq#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hw-yq-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw-yq

tests:
  hw-yq-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw-yq
